Setup FE (#4)
* Add lint rules for FE libs

* Update pre-commit hook to disable committing directly to master

* Add Dockerfile, proper entries to the docker-compose.yml

* Add Portainer as a container mgmt solution to docker-compose.yml

* Add Tailwind CSS, PostCSS, autoprefixer, etc to enable Tailwind support

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,13 @@
 #!/bin/sh
 . "$(dirname $0)/_/husky.sh"
 
+# Prevent commits to master
+branch="$(git rev-parse --abbrev-ref HEAD)"
+
+if [ "$branch" = "master" ]; then
+  echo -e "I can't let you do that Starfox...\nCommits to master are strictly prohibited"
+  exit 1
+fi
+
+# Lint & add files back to staging
 node node_modules/.bin/fizzygalacticus-pre-commit-lint
